In [1]:
from google.colab import files

uploaded = files.upload()

Saving customer.txt to customer.txt
Saving invoice.txt to invoice.txt
Saving payment.txt to payment.txt
Saving product.txt to product.txt
Saving subscription.txt to subscription.txt

In [2]:
import pandas as pd
import numpy as np
import os

In [3]:
def preview_file(filename, n=5):
    print(f"\n===== {filename} =====")

    with open(filename, "r", encoding="utf-8") as f:
        for i in range(n):
            line = f.readline()
            if not line:
                break
            print(repr(line))

In [4]:
preview_file("customer.txt")
preview_file("invoice.txt")
preview_file("payment.txt")
preview_file("product.txt")
preview_file("subscription.txt")

===== customer.txt =====
'+------+-------------------------------+-----------------------------------------------------------------------+--------+---------------------+---------------------+---------------------+\n'
'| id   | Name                          | address                                                               | Gender | phone               | email               | DOB                 |\n'
'+------+-------------------------------+-----------------------------------------------------------------------+--------+---------------------+---------------------+---------------------+\n'
'|    1 | Wani Nurdiyanti               | Psr. Jayawijaya No. 913, Sawahlunto 10252, SulTeng                    | Female | (+62) 976 8680 7043 | waniti@gmail.com    | 1993-05-10 00:00:00 |\n'
'|    2 | Luwes Putra S.I.Kom           | Ki. Yap Tjwan Bing No. 971, Cilegon 53283, Maluku                     | Male   | 0984 8194 3662      | luwespom@gmail.com  | 1999-04-17 00:00:00 |\n'

===== invoice.txt =====
'+------------+---------------+-------------+---------------------+------------+-------------+----------+\n'
'| invoice_id | invoice_code  | customer_id | invoice_date        | product_id | total_price | pinalty  |\n'
'+------------+---------------+-------------+---------------------+------------+-------------+----------+\n'
'|          1 | INV-43378-1   |           1 | 2018-10-05 00:00:00 |      10001 |      100000 | NULL     |\n'
'|          2 | INV-43379-2   |           2 | 2018-10-06 00:00:00 |      10001 |      100000 | NULL     |\n'

===== payment.txt =====
'+------------+------------+----------------+---------------------+\n'
'| payment_id | invoice_id | payment_amount | payment_time        |\n'
'+------------+------------+----------------+---------------------+\n'
'|          1 |          1 |         100000 | 2018-10-06 00:00:00 |\n'
'|          2 |          2 |         100000 | 2018-10-07 00:00:00 |\n'

===== product.txt =====
'+-------+------------------+---------+-------------+---------------------+---------------------+--------+\n'
'| ID    | product_name     | price   | speed_limit | date_active         | end_active          | active |\n'
'+-------+------------------+---------+-------------+---------------------+---------------------+--------+\n'
'| 10001 | Private User     |  100000 |          10 | 2018-10-01 00:00:00 | 2099-12-31 00:00:00 |      1 |\n'
'| 10002 | Family Package   |  250000 |          30 | 2018-10-01 00:00:00 | 2099-12-31 00:00:00 |      1 |\n'

===== subscription.txt =====
'+------+-------------+------------+---------------------+---------------------+\n'
'| Id   | customer_id | product_id | subscription_date   | end_date            |\n'
'+------+-------------+------------+---------------------+---------------------+\n'
'|    1 |           1 |      10001 | 2018-10-05 00:00:00 | 2018-12-03 00:00:00 |\n'
'|    2 |           2 |      10001 | 2018-10-06 00:00:00 | 2099-12-31 00:00:00 |\n'

In [5]:
df_customer = pd.read_csv(
    "customer.txt",
    sep="|",
    engine="python"
)

In [7]:
df_customer.head()
df_customer.head()
df_customer.info()
df_customer.shape
df_customer.isnull().sum()
df_customer.columns

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 53 entries, (nan, ' id   ', ' Name                          ', ' address                                                               ', ' Gender ', ' phone               ', ' email               ', ' DOB                 ') to ('+------+-------------------------------+-----------------------------------------------------------------------+--------+---------------------+---------------------+---------------------+', nan, nan, nan, nan, nan, nan, nan)
Data columns (total 1 columns):
 #   Column                                                                                                                                                                                       Non-Null Count  Dtype
---  ------                                                                                                                                                                                       --------------  -----
 0   +------+-------------------------------+-----------------------------------------------------------------------+--------+---------------------+---------------------+---------------------+  0 non-null      float64
dtypes: float64(1)
memory usage: 15.9+ KB

Index(['+------+-------------------------------+-----------------------------------------------------------------------+--------+---------------------+---------------------+---------------------+'], dtype='object')

In [8]:
df_customer.columns = (
    df_customer.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [9]:
df_customer.head()

                                                                                                                                                                                                                   +------+-------------------------------+-----------------------------------------------------------------------+--------+---------------------+---------------------+---------------------+
NaN                                                id    Name                           address                                        ... Gender  phone                email                DOB                                                                 NaN
+------+-------------------------------+-------... NaN   NaN                            NaN                                                NaN     NaN                  NaN                  NaN                                                                 NaN
NaN                                                   1  Wani Nurdiyanti                Psr. Jayawijaya No. 913, Sawahlunto 10252, SulT... Female  (+62) 976 8680 7043  waniti@gmail.com     1993-05-10 00:00:00                                                 NaN
                                                      2  Luwes Putra S.I.Kom            Ki. Yap Tjwan Bing No. 971, Cilegon 53283, Malu... Male    0984 8194 3662       luwespom@gmail.com   1999-04-17 00:00:00                                                 NaN
                                                      3  Prasetya Karsa Mustofa S.Ked   Psr. Bakin No. 775, Kotamobagu 62174, Lampung  ... Male    (+62) 542 0486 562   praseted@gmail.com   1994-02-03 00:00:00                                                 NaN

In [10]:
string_columns = [
    "name",
    "address",
    "gender",
    "phone",
    "email"
]

for col in string_columns:
    if col in df_customer.columns:
        df_customer[col] = (
            df_customer[col]
            .astype("string")
            .str.strip()
        )

In [11]:
df_customer["id"] = pd.to_numeric(
    df_customer["id"],
    errors="coerce"
)

KeyError: 'id'

In [13]:
print(df_customer.columns.tolist())

['+------+-------------------------------+-----------------------------------------------------------------------+--------+---------------------+---------------------+---------------------+']

In [14]:
print(df_customer.head())

                                                                                                                                                                                                                   +------+-------------------------------+-----------------------------------------------------------------------+--------+---------------------+---------------------+---------------------+
NaN                                                id    Name                           address                                        ... Gender  phone                email                DOB                                                                 NaN
+------+-------------------------------+-------... NaN   NaN                            NaN                                                NaN     NaN                  NaN                  NaN                                                                 NaN
NaN                                                   1  Wani Nurdiyanti                Psr. Jayawijaya No. 913, Sawahlunto 10252, SulT... Female  (+62) 976 8680 7043  waniti@gmail.com     1993-05-10 00:00:00                                                 NaN
                                                      2  Luwes Putra S.I.Kom            Ki. Yap Tjwan Bing No. 971, Cilegon 53283, Malu... Male    0984 8194 3662       luwespom@gmail.com   1999-04-17 00:00:00                                                 NaN
                                                      3  Prasetya Karsa Mustofa S.Ked   Psr. Bakin No. 775, Kotamobagu 62174, Lampung  ... Male    (+62) 542 0486 562   praseted@gmail.com   1994-02-03 00:00:00                                                 NaN

In [15]:
print(df_customer.shape)

(53, 1)

In [16]:
import pandas as pd
import re

def read_mysql_table(filename):
    rows = []

    with open(filename, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()

            # Lewati garis pembatas tabel
            if not line or line.startswith("+"):
                continue

            # Hanya proses baris yang menggunakan |
            if "|" not in line:
                continue

            # Pisahkan berdasarkan |
            parts = [x.strip() for x in line.strip("|").split("|")]

            rows.append(parts)

    # Baris pertama dianggap sebagai header
    header = rows[0]

    # Sisanya adalah data
    data = rows[1:]

    return pd.DataFrame(data, columns=header)

In [17]:
df_customer = read_mysql_table("customer.txt")

In [18]:
print(df_customer.columns.tolist())

['id', 'Name', 'address', 'Gender', 'phone', 'email', 'DOB']

In [19]:
print(df_customer.shape)

(50, 7)

In [20]:
display(df_customer.head())

,id,Name,address,Gender,phone,email,DOB
0,1,Wani Nurdiyanti,"Psr. Jayawijaya No. 913, Sawahlunto 10252, Sul...",Female,(+62) 976 8680 7043,waniti@gmail.com,1993-05-10 00:00:00
1,2,Luwes Putra S.I.Kom,"Ki. Yap Tjwan Bing No. 971, Cilegon 53283, Maluku",Male,0984 8194 3662,luwespom@gmail.com,1999-04-17 00:00:00
2,3,Prasetya Karsa Mustofa S.Ked,"Psr. Bakin No. 775, Kotamobagu 62174, Lampung",Male,(+62) 542 0486 562,praseted@gmail.com,1994-02-03 00:00:00
3,4,Anastasia Ade Safitri,"Gg. Gardujati No. 141, Magelang 24938, JaBar",Female,0748 7971 493,anastri@gmail.com,1998-01-14 00:00:00
4,5,Gaman Tasnim Pratama S.T.,"Ds. Bambon No. 441, Tual 97842, DIY",Male,0277 7636 0163,gamantast@gmail.com,1998-04-24 00:00:00

In [22]:
df_customer.columns = (
    df_customer.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [23]:
print(df_customer.columns.tolist())

['id', 'name', 'address', 'gender', 'phone', 'email', 'dob']

In [24]:
df_customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       50 non-null     object
 1   name     50 non-null     object
 2   address  50 non-null     object
 3   gender   50 non-null     object
 4   phone    50 non-null     object
 5   email    50 non-null     object
 6   dob      50 non-null     object
dtypes: object(7)
memory usage: 2.9+ KB

In [25]:
text_columns = [
    "name",
    "address",
    "gender",
    "phone",
    "email"
]

for col in text_columns:
    df_customer[col] = (
        df_customer[col]
        .astype("string")
        .str.strip()
    )

In [26]:
df_customer["id"] = pd.to_numeric(
    df_customer["id"],
    errors="coerce"
).astype("Int64")

In [27]:
df_customer["gender"] = (
    df_customer["gender"]
    .str.strip()
    .str.title()
)

In [28]:
df_customer["gender"].value_counts(dropna=False)

gender
Female    26
Male      24
Name: count, dtype: Int64

In [29]:
df_customer["dob"] = pd.to_datetime(
    df_customer["dob"],
    errors="coerce"
)

In [30]:
df_customer.isnull().sum()

id         0
name       0
address    0
gender     0
phone      0
email      0
dob        0
dtype: int64

In [31]:
print("Duplicate seluruh baris:", df_customer.duplicated().sum())
print("Duplicate ID:", df_customer["id"].duplicated().sum())

Duplicate seluruh baris: 0
Duplicate ID: 0

In [32]:
df_customer[df_customer["id"].isna()]

Empty DataFrame
Columns: [id, name, address, gender, phone, email, dob]
Index: []

In [33]:
df_customer[df_customer["id"].duplicated(keep=False)]

Empty DataFrame
Columns: [id, name, address, gender, phone, email, dob]
Index: []

In [37]:
NAMA_NIM = "Maulana Aldi Pradana - 24.012459"

In [38]:
df_customer.insert(
    1,
    "nama_nim",
    NAMA_NIM
)

ValueError: cannot insert nama_nim, already exists

In [39]:
if "nama_nim" in df_customer.columns:
    df_customer["nama_nim"] = NAMA_NIM
else:
    df_customer.insert(1, "nama_nim", NAMA_NIM)

In [40]:
print(df_customer.columns.tolist())

['id', 'nama_nim', 'name', 'address', 'gender', 'phone', 'email', 'dob']

In [42]:
# Hapus kolom identitas lama jika sudah ada
for col in ["nama_nim", "nama", "nis"]:
    if col in df_customer.columns:
        df_customer = df_customer.drop(columns=[col])

# Masukkan identitas pada posisi setelah id
df_customer.insert(1, "nama", "Maulana Aldi Pradana")
df_customer.insert(2, "nis", "24.012459")

In [43]:
print(df_customer.columns.tolist())

['id', 'nama', 'nis', 'name', 'address', 'gender', 'phone', 'email', 'dob']

In [45]:
print(df_customer.shape)

(50, 9)

In [46]:
df_invoice = read_mysql_table("invoice.txt")

In [47]:
print(df_invoice.columns.tolist())
print(df_invoice.shape)
display(df_invoice.head())

['invoice_id', 'invoice_code', 'customer_id', 'invoice_date', 'product_id', 'total_price', 'pinalty']
(200, 7)

,invoice_id,invoice_code,customer_id,invoice_date,product_id,total_price,pinalty
0,1,INV-43378-1,1,2018-10-05 00:00:00,10001,100000,NULL
1,2,INV-43379-2,2,2018-10-06 00:00:00,10001,100000,NULL
2,3,INV-43380-3,3,2018-10-07 00:00:00,10003,300000,NULL
3,4,INV-43381-4,4,2018-10-08 00:00:00,10001,100000,NULL
4,5,INV-43382-5,5,2018-10-09 00:00:00,10003,300000,NULL

In [48]:
df_invoice.columns = (
    df_invoice.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

print(df_invoice.columns.tolist())

['invoice_id', 'invoice_code', 'customer_id', 'invoice_date', 'product_id', 'total_price', 'pinalty']

In [49]:
for col in df_invoice.select_dtypes(
    include=["object", "string"]
).columns:
    df_invoice[col] = (
        df_invoice[col]
        .astype("string")
        .str.strip()
    )

In [50]:
for col in ["invoice_id", "customer_id", "product_id"]:
    df_invoice[col] = pd.to_numeric(
        df_invoice[col],
        errors="coerce"
    )

In [51]:
df_invoice["invoice_date"] = pd.to_datetime(
    df_invoice["invoice_date"],
    errors="coerce"
)

In [52]:
df_invoice["total_price"] = pd.to_numeric(
    df_invoice["total_price"],
    errors="coerce"
)

df_invoice["pinalty"] = pd.to_numeric(
    df_invoice["pinalty"],
    errors="coerce"
)

In [53]:
print("Jumlah data:", len(df_invoice))

Jumlah data: 200

In [54]:
print("\nMissing values:")
print(df_invoice.isnull().sum())

Missing values:
invoice_id        0
invoice_code      0
customer_id       0
invoice_date      0
product_id        0
total_price       0
pinalty         170
dtype: int64

In [55]:
print("\nDuplicate rows:")
print(df_invoice.duplicated().sum())

Duplicate rows:
0

In [56]:
print(
    "Duplicate invoice_id:",
    df_invoice["invoice_id"].duplicated().sum()
)

Duplicate invoice_id: 0

In [57]:
invalid_customer = df_invoice[
    ~df_invoice["customer_id"].isin(df_customer["id"])
]

display(invalid_customer)

Empty DataFrame
Columns: [invoice_id, invoice_code, customer_id, invoice_date, product_id, total_price, pinalty]
Index: []

In [59]:
for col in ["nama", "nis"]:
    if col in df_invoice.columns:
        df_invoice = df_invoice.drop(columns=[col])

df_invoice.insert(1, "nama", "Maulana Aldi Pradana")
df_invoice.insert(2, "nis", "24.012459")

In [60]:
print(df_invoice.columns.tolist())

['invoice_id', 'nama', 'nis', 'invoice_code', 'customer_id', 'invoice_date', 'product_id', 'total_price', 'pinalty']

In [61]:
df_invoice.to_csv(
    "invoice_clean.csv",
    index=False
)

In [62]:
print(df_invoice.shape)
print(df_invoice.isnull().sum())
print(df_invoice.duplicated().sum())

(200, 9)
invoice_id        0
nama              0
nis               0
invoice_code      0
customer_id       0
invoice_date      0
product_id        0
total_price       0
pinalty         170
dtype: int64
0

In [63]:
print("Customer ID yang tidak ditemukan:")
display(
    df_invoice[
        ~df_invoice["customer_id"].isin(df_customer["id"])
    ]
)

Customer ID yang tidak ditemukan:

Empty DataFrame
Columns: [invoice_id, nama, nis, invoice_code, customer_id, invoice_date, product_id, total_price, pinalty]
Index: []

In [65]:
invalid_customer = df_invoice[
    ~df_invoice["customer_id"].isin(df_customer["id"])
]

print("Customer ID yang tidak ditemukan:")
display(invalid_customer)

Customer ID yang tidak ditemukan:

Empty DataFrame
Columns: [invoice_id, nama, nis, invoice_code, customer_id, invoice_date, product_id, total_price, pinalty]
Index: []

In [66]:
df_invoice.to_csv(
    "invoice_clean.csv",
    index=False
)

In [69]:
# ============================================
# PROJECT 08 - PAYMENT DATA CLEANING
# ============================================

import pandas as pd

# --------------------------------------------
# 1. Baca file tabel ASCII/MySQL
# --------------------------------------------

def read_mysql_table(filename):
    rows = []

    with open(filename, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()

            # Lewati baris kosong dan garis pembatas
            if not line or line.startswith("+"):
                continue

            # Hanya ambil baris tabel
            if "|" not in line:
                continue

            parts = [
                x.strip()
                for x in line.strip("|").split("|")
            ]

            rows.append(parts)

    if not rows:
        raise ValueError(f"Tidak ada data tabel yang ditemukan pada {filename}")

    # Baris pertama = header
    header = rows[0]

    # Baris berikutnya = data
    data = rows[1:]

    return pd.DataFrame(data, columns=header)


# --------------------------------------------
# 2. Load Payment
# --------------------------------------------

df_payment = read_mysql_table("payment.txt")

# --------------------------------------------
# 3. Bersihkan nama kolom
# --------------------------------------------

df_payment.columns = (
    df_payment.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

print("Kolom Payment:")
print(df_payment.columns.tolist())

# --------------------------------------------
# 4. Bersihkan nilai string
# --------------------------------------------

for col in df_payment.select_dtypes(
    include=["object", "string"]
).columns:
    df_payment[col] = (
        df_payment[col]
        .astype("string")
        .str.strip()
    )


# --------------------------------------------
# 5. Tampilkan struktur sebelum konversi
# --------------------------------------------

print("\nShape:")
print(df_payment.shape)

print("\nPreview:")
display(df_payment.head())


# --------------------------------------------
# 6. Konversi ID
# --------------------------------------------

if "id" in df_payment.columns:
    df_payment["id"] = pd.to_numeric(
        df_payment["id"],
        errors="coerce"
    ).astype("Int64")

if "invoice_id" in df_payment.columns:
    df_payment["invoice_id"] = pd.to_numeric(
        df_payment["invoice_id"],
        errors="coerce"
    ).astype("Int64")


# --------------------------------------------
# 7. Konversi amount
# --------------------------------------------

if "amount" in df_payment.columns:
    df_payment["amount"] = pd.to_numeric(
        df_payment["amount"],
        errors="coerce"
    )


# --------------------------------------------
# 8. Konversi payment_date
# --------------------------------------------

if "payment_date" in df_payment.columns:
    df_payment["payment_date"] = pd.to_datetime(
        df_payment["payment_date"],
        errors="coerce"
    )


# --------------------------------------------
# 9. Tambahkan Nama dan NIS
# --------------------------------------------

for col in ["nama", "nis"]:
    if col in df_payment.columns:
        df_payment = df_payment.drop(columns=[col])

df_payment.insert(
    1,
    "nama",
    "Maulana Aldi Pradana"
)

df_payment.insert(
    2,
    "nis",
    "24.012459"
)


# --------------------------------------------
# 10. Validasi relasi Payment -> Invoice
# --------------------------------------------

if (
    "invoice_id" in df_payment.columns
    and "invoice_id" in df_invoice.columns
):
    invalid_invoice = df_payment[
        ~df_payment["invoice_id"].isin(
            df_invoice["invoice_id"]
        )
    ]
else:
    invalid_invoice = pd.DataFrame()


# --------------------------------------------
# 11. HASIL AKHIR
# --------------------------------------------

print("\n" + "=" * 50)
print("PAYMENT - HASIL CLEANING")
print("=" * 50)

print("\nShape:")
print(df_payment.shape)

print("\nColumns:")
print(df_payment.columns.tolist())

print("\nMissing Values:")
print(df_payment.isnull().sum())

print("\nDuplicate Rows:")
print(df_payment.duplicated().sum())

if "id" in df_payment.columns:
    print("\nDuplicate Payment ID:")
    print(df_payment["id"].duplicated().sum())

print("\nInvoice ID yang tidak ditemukan:")
print(len(invalid_invoice))

if len(invalid_invoice) > 0:
    display(invalid_invoice)

print("\nPreview:")
display(df_payment.head())


# --------------------------------------------
# 12. Export
# --------------------------------------------

df_payment.to_csv(
    "payment_clean.csv",
    index=False
)

print("\nFile berhasil dibuat:")
print("payment_clean.csv")

Kolom Payment:
['payment_id', 'invoice_id', 'payment_amount', 'payment_time']

Shape:
(200, 4)

Preview:

  payment_id invoice_id payment_amount         payment_time
0          1          1         100000  2018-10-06 00:00:00
1          2          2         100000  2018-10-07 00:00:00
2          3          3         300000  2018-10-08 00:00:00
3          4          4         100000  2018-10-09 00:00:00
4          5          5         300000  2018-10-10 00:00:00

==================================================
PAYMENT - HASIL CLEANING
==================================================

Shape:
(200, 6)

Columns:
['payment_id', 'nama', 'nis', 'invoice_id', 'payment_amount', 'payment_time']

Missing Values:
payment_id        0
nama              0
nis               0
invoice_id        0
payment_amount    0
payment_time      0
dtype: int64

Duplicate Rows:
0

Invoice ID yang tidak ditemukan:
0

Preview:

,payment_id,nama,nis,invoice_id,payment_amount,payment_time
0,1,Maulana Aldi Pradana,24.012459,1,100000,2018-10-06 00:00:00
1,2,Maulana Aldi Pradana,24.012459,2,100000,2018-10-07 00:00:00
2,3,Maulana Aldi Pradana,24.012459,3,300000,2018-10-08 00:00:00
3,4,Maulana Aldi Pradana,24.012459,4,100000,2018-10-09 00:00:00
4,5,Maulana Aldi Pradana,24.012459,5,300000,2018-10-10 00:00:00

File berhasil dibuat:
payment_clean.csv

In [70]:
df_product = read_mysql_table("product.txt")

df_product.columns = (
    df_product.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

print("Kolom Product:")
print(df_product.columns.tolist())

print("\nShape:")
print(df_product.shape)

print("\nPreview:")
display(df_product.head())

Kolom Product:
['id', 'product_name', 'price', 'speed_limit', 'date_active', 'end_active', 'active']

Shape:
(5, 7)

Preview:

,id,product_name,price,speed_limit,date_active,end_active,active
0,10001,Private User,100000,10,2018-10-01 00:00:00,2099-12-31 00:00:00,1
1,10002,Family Package,250000,30,2018-10-01 00:00:00,2099-12-31 00:00:00,1
2,10003,Faster Package,300000,50,2018-10-01 00:00:00,2099-12-31 00:00:00,1
3,10004,Gamer Package,500000,100,2018-10-01 00:00:00,2099-12-31 00:00:00,1
4,10005,Bussines Package,1200000,500,2018-12-01 00:00:00,2099-12-31 00:00:00,1

In [71]:
# ============================================
# PROJECT 08 - PRODUCT DATA CLEANING
# ============================================

import pandas as pd

# 1. Load Product.txt
df_product = read_mysql_table("product.txt")

# 2. Bersihkan nama kolom
df_product.columns = (
    df_product.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

# 3. Bersihkan kolom teks
for col in df_product.select_dtypes(
    include=["object", "string"]
).columns:
    df_product[col] = (
        df_product[col]
        .astype("string")
        .str.strip()
    )

# 4. Konversi ID
df_product["id"] = pd.to_numeric(
    df_product["id"],
    errors="coerce"
).astype("Int64")

# 5. Konversi harga
df_product["price"] = pd.to_numeric(
    df_product["price"],
    errors="coerce"
)

# 6. Konversi speed limit
df_product["speed_limit"] = pd.to_numeric(
    df_product["speed_limit"],
    errors="coerce"
)

# 7. Konversi tanggal
df_product["date_active"] = pd.to_datetime(
    df_product["date_active"],
    errors="coerce"
)

df_product["end_active"] = pd.to_datetime(
    df_product["end_active"],
    errors="coerce"
)

# 8. Konversi active
df_product["active"] = pd.to_numeric(
    df_product["active"],
    errors="coerce"
).astype("Int64")

# 9. Tambahkan nama dan NIS
for col in ["nama", "nis"]:
    if col in df_product.columns:
        df_product = df_product.drop(columns=[col])

df_product.insert(
    1,
    "nama",
    "Maulana Aldi Pradana"
)

df_product.insert(
    2,
    "nis",
    "24.012459"
)

# 10. Validasi ID
duplicate_product_id = df_product[
    df_product["id"].duplicated(keep=False)
]

# 11. Validasi relasi Product -> Invoice
invalid_product_invoice = df_invoice[
    ~df_invoice["product_id"].isin(
        df_product["id"]
    )
]

# 12. Validasi relasi Product -> Subscription
# Dilakukan nanti setelah Subscription selesai
invalid_product_subscription = pd.DataFrame()

# ============================================
# HASIL CLEANING
# ============================================

print("=" * 50)
print("PRODUCT - HASIL CLEANING")
print("=" * 50)

print("\nShape:")
print(df_product.shape)

print("\nColumns:")
print(df_product.columns.tolist())

print("\nMissing Values:")
print(df_product.isnull().sum())

print("\nDuplicate Rows:")
print(df_product.duplicated().sum())

print("\nDuplicate Product ID:")
print(df_product["id"].duplicated().sum())

print("\nProduct ID yang tidak ditemukan pada Invoice:")
print(len(invalid_product_invoice))

if len(invalid_product_invoice) > 0:
    display(invalid_product_invoice)

print("\nPreview:")
display(df_product)

# 13. Export
df_product.to_csv(
    "product_clean.csv",
    index=False
)

print("\nFile berhasil dibuat:")
print("product_clean.csv")

==================================================
PRODUCT - HASIL CLEANING
==================================================

Shape:
(5, 9)

Columns:
['id', 'nama', 'nis', 'product_name', 'price', 'speed_limit', 'date_active', 'end_active', 'active']

Missing Values:
id              0
nama            0
nis             0
product_name    0
price           0
speed_limit     0
date_active     0
end_active      0
active          0
dtype: int64

Duplicate Rows:
0

Duplicate Product ID:
0

Product ID yang tidak ditemukan pada Invoice:
0

Preview:

,id,nama,nis,product_name,price,speed_limit,date_active,end_active,active
0,10001,Maulana Aldi Pradana,24.012459,Private User,100000,10,2018-10-01,2099-12-31,1
1,10002,Maulana Aldi Pradana,24.012459,Family Package,250000,30,2018-10-01,2099-12-31,1
2,10003,Maulana Aldi Pradana,24.012459,Faster Package,300000,50,2018-10-01,2099-12-31,1
3,10004,Maulana Aldi Pradana,24.012459,Gamer Package,500000,100,2018-10-01,2099-12-31,1
4,10005,Maulana Aldi Pradana,24.012459,Bussines Package,1200000,500,2018-12-01,2099-12-31,1

File berhasil dibuat:
product_clean.csv

In [72]:
# ============================================
# LOAD SUBSCRIPTION
# ============================================

df_subscription = read_mysql_table("subscription.txt")

df_subscription.columns = (
    df_subscription.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

print("Kolom Subscription:")
print(df_subscription.columns.tolist())

print("\nShape:")
print(df_subscription.shape)

print("\nPreview:")
display(df_subscription.head())

Kolom Subscription:
['id', 'customer_id', 'product_id', 'subscription_date', 'end_date']

Shape:
(56, 5)

Preview:

  id customer_id product_id    subscription_date             end_date
0  1           1      10001  2018-10-05 00:00:00  2018-12-03 00:00:00
1  2           2      10001  2018-10-06 00:00:00  2099-12-31 00:00:00
2  3           3      10003  2018-10-07 00:00:00  2099-12-31 00:00:00
3  4           4      10001  2018-10-08 00:00:00  2099-12-31 00:00:00
4  5           5      10003  2018-10-09 00:00:00  2099-12-31 00:00:00

In [74]:
# ============================================
# PROJECT 08 - SUBSCRIPTION DATA CLEANING
# ============================================

import pandas as pd

# 1. Load Subscription
df_subscription = read_mysql_table("subscription.txt")

# 2. Bersihkan nama kolom
df_subscription.columns = (
    df_subscription.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

# 3. Bersihkan kolom teks
for col in df_subscription.select_dtypes(
    include=["object", "string"]
).columns:
    df_subscription[col] = (
        df_subscription[col]
        .astype("string")
        .str.strip()
    )

# 4. Konversi ID
for col in ["id", "customer_id", "product_id"]:
    df_subscription[col] = pd.to_numeric(
        df_subscription[col],
        errors="coerce"
    ).astype("Int64")

# 5. Konversi tanggal
df_subscription["subscription_date"] = pd.to_datetime(
    df_subscription["subscription_date"],
    errors="coerce"
)

df_subscription["end_date"] = pd.to_datetime(
    df_subscription["end_date"],
    errors="coerce"
)

# 6. Tambahkan nama dan NIS
for col in ["nama", "nis"]:
    if col in df_subscription.columns:
        df_subscription = df_subscription.drop(columns=[col])

df_subscription.insert(
    1,
    "nama",
    "Maulana Aldi Pradana"
)

df_subscription.insert(
    2,
    "nis",
    "24.012459"
)

# ============================================
# VALIDASI
# ============================================

# Validasi ID Subscription
duplicate_subscription_id = df_subscription[
    df_subscription["id"].duplicated(keep=False)
]

# Validasi Customer
invalid_customer = df_subscription[
    ~df_subscription["customer_id"].isin(
        df_customer["id"]
    )
]

# Validasi Product
invalid_product = df_subscription[
    ~df_subscription["product_id"].isin(
        df_product["id"]
    )
]

# ============================================
# HASIL CLEANING
# ============================================

print("=" * 50)
print("SUBSCRIPTION - HASIL CLEANING")
print("=" * 50)

print("\nShape:")
print(df_subscription.shape)

print("\nColumns:")
print(df_subscription.columns.tolist())

print("\nMissing Values:")
print(df_subscription.isnull().sum())

print("\nDuplicate Rows:")
print(df_subscription.duplicated().sum())

print("\nDuplicate Subscription ID:")
print(df_subscription["id"].duplicated().sum())

print("\nCustomer ID yang tidak ditemukan:")
print(len(invalid_customer))

if len(invalid_customer) > 0:
    display(invalid_customer)

print("\nProduct ID yang tidak ditemukan:")
print(len(invalid_product))

if len(invalid_product) > 0:
    display(invalid_product)

print("\nPreview:")
display(df_subscription.head())

# ============================================
# EXPORT
# ============================================

df_subscription.to_csv(
    "subscription_clean.csv",
    index=False
)

print("\nFile berhasil dibuat:")
print("subscription_clean.csv")

==================================================
SUBSCRIPTION - HASIL CLEANING
==================================================

Shape:
(56, 7)

Columns:
['id', 'nama', 'nis', 'customer_id', 'product_id', 'subscription_date', 'end_date']

Missing Values:
id                   0
nama                 0
nis                  0
customer_id          0
product_id           0
subscription_date    0
end_date             0
dtype: int64

Duplicate Rows:
0

Duplicate Subscription ID:
0

Customer ID yang tidak ditemukan:
0

Product ID yang tidak ditemukan:
0

Preview:

,id,nama,nis,customer_id,product_id,subscription_date,end_date
0,1,Maulana Aldi Pradana,24.012459,1,10001,2018-10-05,2018-12-03
1,2,Maulana Aldi Pradana,24.012459,2,10001,2018-10-06,2099-12-31
2,3,Maulana Aldi Pradana,24.012459,3,10003,2018-10-07,2099-12-31
3,4,Maulana Aldi Pradana,24.012459,4,10001,2018-10-08,2099-12-31
4,5,Maulana Aldi Pradana,24.012459,5,10003,2018-10-09,2099-12-31

File berhasil dibuat:
subscription_clean.csv

In [75]:
import os

files = [
    "customer_clean.csv",
    "invoice_clean.csv",
    "payment_clean.csv",
    "product_clean.csv",
    "subscription_clean.csv"
]

for file in files:
    print(
        "✅" if os.path.exists(file) else "❌",
        file
    )

❌ customer_clean.csv
✅ invoice_clean.csv
✅ payment_clean.csv
✅ product_clean.csv
✅ subscription_clean.csv

In [76]:
# ============================================
# CUSTOMER - CLEANING & TRANSFORM
# ============================================

import pandas as pd

# 1. Load Customer.txt
df_customer = read_mysql_table("customer.txt")

# 2. Bersihkan nama kolom
df_customer.columns = (
    df_customer.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

print("Kolom awal:")
print(df_customer.columns.tolist())

# 3. Bersihkan kolom teks
for col in df_customer.select_dtypes(
    include=["object", "string"]
).columns:
    df_customer[col] = (
        df_customer[col]
        .astype("string")
        .str.strip()
    )

# 4. Konversi ID
df_customer["id"] = pd.to_numeric(
    df_customer["id"],
    errors="coerce"
).astype("Int64")

# 5. Konversi tanggal lahir
df_customer["dob"] = pd.to_datetime(
    df_customer["dob"],
    errors="coerce"
)

# ============================================
# 6. TAMBAHKAN NAMA & NIS
# ============================================

NAMA_KAMU = "Maulana Aldi Pradana"
NIS_KAMU = "24.012459"

# Hapus jika sebelumnya sudah pernah dibuat
for col in ["nama", "nis"]:
    if col in df_customer.columns:
        df_customer = df_customer.drop(columns=[col])

# Nama menjadi kolom kedua
df_customer.insert(
    1,
    "nama",
    NAMA_KAMU
)

# NIS menjadi kolom ketiga
df_customer.insert(
    2,
    "nis",
    NIS_KAMU
)

# ============================================
# 7. VALIDASI
# ============================================

duplicate_id = df_customer["id"].duplicated().sum()

# ============================================
# 8. HASIL CLEANING
# ============================================

print("=" * 50)
print("CUSTOMER - HASIL CLEANING")
print("=" * 50)

print("\nShape:")
print(df_customer.shape)

print("\nColumns:")
print(df_customer.columns.tolist())

print("\nMissing Values:")
print(df_customer.isnull().sum())

print("\nDuplicate Rows:")
print(df_customer.duplicated().sum())

print("\nDuplicate Customer ID:")
print(duplicate_id)

print("\nPreview:")
display(df_customer.head())

# ============================================
# 9. EXPORT
# ============================================

df_customer.to_csv(
    "customer_clean.csv",
    index=False
)

print("\nFile berhasil dibuat:")
print("customer_clean.csv")

Kolom awal:
['id', 'name', 'address', 'gender', 'phone', 'email', 'dob']
==================================================
CUSTOMER - HASIL CLEANING
==================================================

Shape:
(50, 9)

Columns:
['id', 'nama', 'nis', 'name', 'address', 'gender', 'phone', 'email', 'dob']

Missing Values:
id         0
nama       0
nis        0
name       0
address    0
gender     0
phone      0
email      0
dob        0
dtype: int64

Duplicate Rows:
0

Duplicate Customer ID:
0

Preview:

,id,nama,nis,name,address,gender,phone,email,dob
0,1,Maulana Aldi Pradana,24.012459,Wani Nurdiyanti,"Psr. Jayawijaya No. 913, Sawahlunto 10252, Sul...",Female,(+62) 976 8680 7043,waniti@gmail.com,1993-05-10
1,2,Maulana Aldi Pradana,24.012459,Luwes Putra S.I.Kom,"Ki. Yap Tjwan Bing No. 971, Cilegon 53283, Maluku",Male,0984 8194 3662,luwespom@gmail.com,1999-04-17
2,3,Maulana Aldi Pradana,24.012459,Prasetya Karsa Mustofa S.Ked,"Psr. Bakin No. 775, Kotamobagu 62174, Lampung",Male,(+62) 542 0486 562,praseted@gmail.com,1994-02-03
3,4,Maulana Aldi Pradana,24.012459,Anastasia Ade Safitri,"Gg. Gardujati No. 141, Magelang 24938, JaBar",Female,0748 7971 493,anastri@gmail.com,1998-01-14
4,5,Maulana Aldi Pradana,24.012459,Gaman Tasnim Pratama S.T.,"Ds. Bambon No. 441, Tual 97842, DIY",Male,0277 7636 0163,gamantast@gmail.com,1998-04-24

File berhasil dibuat:
customer_clean.csv

In [77]:
import os

print(os.path.exists("customer_clean.csv"))

True

In [78]:
from google.colab import files

files.download("customer_clean.csv")

In [79]:
import os

files = [
    "customer_clean.csv",
    "invoice_clean.csv",
    "payment_clean.csv",
    "product_clean.csv",
    "subscription_clean.csv"
]

print("CHECK FILE PROJECT 08")
print("=" * 40)

for file in files:
    if os.path.exists(file):
        print(f"✅ {file}")
    else:
        print(f"❌ {file}")

CHECK FILE PROJECT 08
========================================
✅ customer_clean.csv
✅ invoice_clean.csv
✅ payment_clean.csv
✅ product_clean.csv
✅ subscription_clean.csv

In [80]:
import zipfile

files = [
    "customer_clean.csv",
    "invoice_clean.csv",
    "payment_clean.csv",
    "product_clean.csv",
    "subscription_clean.csv"
]

with zipfile.ZipFile(
    "project-08-clean-data.zip",
    "w",
    zipfile.ZIP_DEFLATED
) as zipf:

    for file in files:
        zipf.write(file)

print("✅ project-08-clean-data.zip berhasil dibuat")

✅ project-08-clean-data.zip berhasil dibuat

In [81]:
from google.colab import files

files.download("project-08-clean-data.zip")